test-service:
  image: docker.sytac.io:443/resumator-service:develop
  command: -Dresumator.http.context.path=api/
  links:
    - test-db
test-db:
  image: postgres
  environment:
    - POSTGRES_USER=resumator
    - POSTGRES_PASSWORD=resumator
    - POSTGRES_DB=resumator
test-ui:
  image: docker.sytac.ieo:443/resumator-ui:develop
test-lb:
  image: docker.sytac.io:443/resumator-load-balancer:develop
  ports:
    - "9000:80"
  links:
    - test-ui
    - test-service
