service:
  image: docker.sytac.io:443/resumator-service:latest
  command: -Dresumator.http.context.path=api/
  links:
    - db
  volumes:
    - ${RESUMATOR_CONFIG}:/root/.resumator
db:
  image: postgres
  environment:
    - POSTGRES_USER=resumator
    - POSTGRES_PASSWORD=resumator
    - POSTGRES_DB=resumator
ui:
  image: docker.sytac.io:443/resumator-ui:latest
lb:
  image: docker.sytac.io:443/resumator-load-balancer:latest
  ports:
    - "8000:80"
  links:
    - ui
    - service
