testservice:
  image: docker.sytac.io:443/resumator-service:develop
  command: -Dresumator.http.context.path=api/
  links:
    - testdb
  volumes:
    - ${RESUMATOR_CONFIG}:/root/.resumator
testdb:
  image: postgres
  environment:
    - POSTGRES_USER=resumator
    - POSTGRES_PASSWORD=resumator
    - POSTGRES_DB=resumator
testui:
  image: docker.sytac.io:443/resumator-ui:develop
testlb:
  image: docker.sytac.io:443/resumator-load-balancer:develop
  ports:
    - "9000:80"
  links:
    - testui
    - testservice
