service:
  image: resumator-service
  command: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Dresumator.http.context.path=api/
  links:
    - db
  volumes:
    - ${RESUMATOR_CONFIG}:/root/.resumator/config.properties
  ports:
    - "5005:5005"
db:
  image: postgres
  environment:
    - POSTGRES_USER=resumator
    - POSTGRES_PASSWORD=resumator
    - POSTGRES_DB=resumator
  ports:
    - "5432:5432"
ui:
  image: resumator-ui
  volumes:
    - ../resumator-ui/docker/nginx-dev.conf:/etc/nginx/conf.d/resumator.conf
    - ../resumator-ui/build:/usr/share/nginx/html/
lb:
  image: resumator-load-balancer
  ports:
    - "8000:80"
  links:
    - ui
    - service
