testservice:
  image: resumator-service
  command: -Dresumator.http.context.path=api/
  links:
    - testdb
  volumes:
    - ${RESUMATOR_CONFIG}:/etc/resumator
testdb:
  image: postgres
  environment:
    - POSTGRES_USER=resumator
    - POSTGRES_PASSWORD=resumator
    - POSTGRES_DB=resumator
  ports:
    - "5432:5432"
testui:
  image: resumator-ui
  volumes:
    - ../resumator-ui/docker/nginx-dev.conf:/etc/nginx/conf.d/resumator.conf
    - ../resumator-ui/build:/usr/share/nginx/html/
testlb:
  image: resumator-load-balancer
  ports:
    - "8000:80"
  links:
    - testui
    - testservice
