// Node libraries
var fs = require('fs');

// Gulp system
var gulp = require('gulp');
var plugins = require('gulp-load-plugins')();
var gulpHelp = require('gulp-help');
var gutil = require('gulp-util');
gulp = gulpHelp(gulp);

// Gulp plugins
var browserify = require('browserify');
var buffer = require('vinyl-buffer');
var del = require('del');
var gutil = require('gulp-util');
var liveServer = require('live-server');
var pngquant = require('imagemin-pngquant');
var runSequence = require('run-sequence');
var source = require('vinyl-source-stream');
var uglify = require('gulp-uglify');
var watchify = require('watchify');

// Error handling
function handleError(taskName, error) {
  throw new gutil.PluginError(taskName, error, {
    showStack: true
  });

  //gutil.log(error)
  //console.error(error.message && error.stack && error.message + '\n\n' + error.stack || error.message || error.stack || error);
}

// Browserify
function getBundle(path) {
  return browserify({
    entries: path,
    // debug: true,
    transform: []
  });
}
function runBundle() {
  return function(bundle, cb) {
    bundle
      .bundle()
      .pipe(source('app.bundle.js'))
      .pipe(gulp.dest('build/client/js'))
      .on('end', cb);
  };
}

gulp.task('cleanDirectory', 'Cleans the build directory, starting every run with a clean slate.', function() {
  return del([ 'build/**/*' ]);
});

gulp.task('compileBabel', 'Compiles all JavaScript files from ES2015 to ES5 with Babel.js from the source directory to the build directory.', function(cb) {
  return gulp.src('src/**/*.js')
    .pipe(plugins.changed('build'))
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.babel({
      presets: [ 'es2015', 'react', 'stage-0' ]
    }))
    .on('error', function(error) {
      handleError('compileBabel', error);
      cb();
    })
    .pipe(plugins.sourcemaps.write())
    .pipe(gulp.dest('build'))
});

gulp.task('compileBrowserify', 'Compiles the client JavaScript code from the build directory into one file in the build directory with Browserify.', function compileBrowserify(cb) {
  var path = 'build/client/js/app.js';

  fs.exists(path, function(doesExist) {
    if (!doesExist) {
      return cb();
    }

    var bundle = getBundle(path);

    runBundle()(bundle, cb);
  });
});

gulp.task('compileImages', 'Minifies all GIF, JPG, PNG and SVG images from the source directory into the build directory.', function compileImages() {
  return gulp.src('src/**/*.@(gif|jpg|png|svg)')
    .pipe(plugins.changed('build'))
    .pipe(plugins.imagemin({
      progressive: true,
      svgoPlugins: [ { removeViewbox: false } ],
      use: [ pngquant() ]
    }))
    .pipe(gulp.dest('build'));
});

gulp.task('compileLess', 'Compiles all LESS files to CSS from the source directory to the build directory.', function compileLess() {
  return gulp.src('src/client/styles/app.less')
    .pipe(plugins.changed('build'))
    .pipe(plugins.less())
    .pipe(plugins.cssnano())
    .pipe(gulp.dest('build/client/css'));
});

gulp.task('compileCopy', 'Copies over all files that are not compiled by another task from the source directory to the build directory.', function compileCopy() {
  return gulp.src('src/**/*.!(gif|jpg|png|svg|less|js)')
    .pipe(plugins.changed('build'))
    .pipe(gulp.dest('build'));
});

gulp.task('minifyJavaScript', 'Minifies the client javascript bundle generated by Browserify.', function minifyJavaScript() {
  return gulp.src('build/client/js/app.bundle.js')
    .pipe(uglify())
    .pipe(gulp.dest('build/client/js'));
});

gulp.task('minifyHTML', 'Minifies all HTML files and puts them in the build directory.', function minifyJavaScript() {
  return gulp.src('build/**/*.html')
    .pipe(plugins.htmlmin({
      removeComments: true,
      removeCommentsFromCDATA: true,
      removeCDATASectionsFromCDATA: true,
      removeAttributeQuotes: true,
      removeRedundantAttributes: true,
      useShortDoctype: true,
      collapseWhitespace: true
    }))
    .pipe(gulp.dest('build'));
});

// TODO: Allow a way to use this HTTP server to serve the frontend and also
// proxy any requests that are not static files to a configured API server.
gulp.task('runLiveServer', 'Runs a `live-server` HTTP server, serving all of the client side files from the build directory.', function runLiveServer(cb) {
  liveServer.start({
    port: 8080,
    host: '0.0.0.0',
    root: 'build/client',
    open: false,
    file: 'index.html',
    wait: 1000
  });

  cb();
});

gulp.task('runServer', 'Runs the API server.', function runServer(cb) {
  var path = __dirname + '/build/server/app.js';

  fs.exists(path, function(doesExist) {
    if (!doesExist) {
      gutil.log('runServer', 'Path `' + path + '` does not exist, skipping task.');
      return cb();
    }

    plugins.developServer.listen({
      path: path
    });

    plugins.saneWatch('build/server/**/*', { debounce: 300 }, function() {
      plugins.developServer.restart();
    });

    cb();
  });
});

gulp.task('runTests', 'Runs all tests from the source directory with Mocha.', function runTests() {
  return gulp.src('src/test/**/*.js', { read: false })
    .pipe(plugins.mocha({
      recursive: true,
      reporter: 'spec'
    }));
});

gulp.task('watchBrowserify', 'Watches the build directory for new files that get compiled to there and re-compiles the client code with browserify when that happens.', function watchBrowserify(cb) {
  var path = 'build/client/js/app.js';

  fs.exists(path, function(doesExist) {
    if (!doesExist) {
      return cb();
    }

    var bundle = watchify(getBundle(path));

    bundle.on('update', function() {
      runBundle()(bundle, function() {});
    });

    bundle.on('log', gutil.log);

    runBundle()(bundle, function() {});

    cb();
  });
});

gulp.task('watchCompilers', 'Watches the source directory and runs compile tasks when changes happen.', function watchCompilers(cb) {
  plugins.saneWatch('src/**/*', { debounce: 300 }, function(filename, path, stat) {
    if (filename.match(/^.*\.js$/)) {
      gulp.start('compileBabel');
    }

    if (filename.match(/^.*\.less$/)) {
      gulp.start('compileLess');
    }

    if (filename.match(/^.*\.(gif|jpg|png|svg)$/)) {
      gulp.start('compileImages');
    }

    if (!filename.match(/^.*\.(gif|jpg|png|svg|less|js)$/)) {
      gulp.start('compileCopy');
    }
  });

  cb();
});

gulp.task('watchTests', 'Watches the source tests directory and re-runs tests when changes happen.', function watchTests(cb) {
  gulp.watch('src/**/*.js', [ 'runTests' ]);

  cb();
});

gulp.task('develop', 'Runs all tasks required for development.', function(cb) {
  runSequence(
    'cleanDirectory',

    [
      'compileBabel',
      'compileCopy',
      'compileImages',
      'compileLess'
    ],

    'runTests',

    [
      'runServer',
      'runLiveServer',
      'watchBrowserify',
      'watchTests',
      'watchCompilers'
    ],

    cb
  );
});

gulp.task('production', 'Runs all tasks required for production.', function(cb) {
  runSequence(
    'cleanDirectory',

    [
      'compileBabel',
      'compileCopy',
      'compileImages',
      'compileLess'
    ],

    'compileBrowserify',

    [
      'minifyJavaScript',
      'minifyHTML'
    ],

    cb
  );
});
